version: '3.5'
services:

  # THIS RUNS A LOCAL NGINX PROXY TO A LOCAL KIMAI RUNNING IN DEV MODE

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai

  kimai:
    image: kimai/kimai2:fpm-latest-dev
    environment:
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
    volumes:
      - public:/opt/kimai/public
    restart: unless-stopped

  # Needed for Kimai
  sqldb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

volumes:
    public:
    sqldb:
